version: '3.6'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: film_saver
      POSTGRES_DB: film_saver
      POSTGRES_PASSWORD: film_saver
    ports:
      - 5432:5432
    volumes:
      - /Users/igordrozdov/IdeaProjects/film-explorer/database:/var/lib/postgresql

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    environment:
      - cluster.name=elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /Users/igordrozdov/IdeaProjects/film-explorer/es_data:/usr/share/elasticsearch/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "film"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  film-saver:
    image: film-saver:latest
    links:
      - kafka
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: db
      KAFKA_URL: kafka
    depends_on:
      - kafka
      - zookeeper
      - db

  film-search:
    image: film-search:latest
    links:
      - kafka
      - es
    ports:
      - "8090:8080"
    environment:
      ELASTIC_URL: es
      KAFKA_URL: kafka
    depends_on:
      - kafka
      - zookeeper
      - es
